// Generated by CoffeeScript 1.10.0
'use strict';
var JSTimeLinter;

JSTimeLinter = (function() {
  function JSTimeLinter() {
    this.col = ['yellow', 'green', 'red', 'blue'];
    this.step = 1;
  }

  JSTimeLinter.prototype.run = function() {};

  JSTimeLinter.prototype.stop = function() {};

  JSTimeLinter.prototype.pause = function() {};

  JSTimeLinter.prototype.reset = function() {};

  JSTimeLinter.prototype.getJs = function(js_code) {
    return console.log(js_code);
  };

  return JSTimeLinter;

})();
